refactor: from get-branches to get-original

diff --git a/get-original b/get-original
--- a/get-original
+++ b/get-original
@@ -4,20 +4,19 @@ dpg_extension="dpg"
 
 # Check if we are inside a Git repository
 if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
-	echo "ERROR: Not inside a Git repository" >&2
-	exit 1
+    echo "ERROR: Not inside a Git repository" >&2
+    exit 1
 fi
 
 # Get branch name
 branch=$(git symbolic-ref --short HEAD)
 
 if [[ $branch != *.${dpg_extension} ]]; then
-	echo "ERROR: Branch $branch is not a doppelganger!" >&2
-	exit 1
+    echo "ERROR: Branch $branch is not a doppelganger!" >&2
+    exit 1
 fi
 
-dpg_branch=$branch
 original_branch=${branch%.$dpg_extension}
 
-echo "$dpg_branch $original_branch"
+echo "$original_branch"
 
