fix: echo to stderr in git-dpg

diff --git a/git-dpg b/git-dpg
--- a/git-dpg
+++ b/git-dpg
@@ -5,7 +5,7 @@ commands_dir=$(dirname $0)/git-dpg-commands
 command=$1
 
 if [ -z "$command" ]; then
-    echo "Error: No command provided"
+    >&2 echo "Error: No command provided"
     exit 1
 fi
 
