doppelganger v2

diff --git a/utils/update-original b/utils/update-original
--- a/utils/update-original
+++ b/utils/update-original
@@ -1,12 +1,16 @@
 #!/bin/bash
 
-new_dpg_base_commit=""
+set -eu
+
+diff=$(cat -)
+
+new_base_commit=""
 commit_message=""
 
 while getopts "b:m:" opt; do
     case $opt in
         b)
-            new_dpg_base_commit=$OPTARG
+            new_base_commit=$OPTARG
             ;;
         m)
             commit_message=$OPTARG
@@ -20,19 +24,13 @@ done
 shift $((OPTIND - 1))
 
 original_branch=$1
-old_dpg_commit=$2
-new_dpg_commit=$3
 
-if [[ -z $original_branch || -z $old_dpg_commit || -z $new_dpg_commit ]]; then
-    echo "Error: some of the mandatory arguments are missing" >&2
-    echo "original_branch: $original_branch"
-    echo "old_dpg_commit: $old_dpg_commit"
-    echo "new_dpg_commit: $new_dpg_commit"
+if [ -z "$original_branch" ]; then
+    >&2 echo "Error: original branch not provided"
     exit 1
 fi
 
-diff=$(git diff $old_dpg_commit $new_dpg_commit)
-if [ -z "$diff" ]; then
+if [[ -z "$diff" && -z "$rebasing_commit" ]]; then
     echo "No difference between old and new doppelganger, no need to update original"
     exit 0
 fi
@@ -71,8 +69,8 @@ fi
 # Switch to the original branch to update it
 git switch $original_branch
 
-if [ -n "$new_dpg_base_commit" ]; then
-    git merge --no-commit $new_dpg_base_commit
+if [ -n "$new_base_commit" ]; then
+    git merge --no-commit $new_base_commit
 fi
 
 # Restore state of the repository without aborting the merge, if any
@@ -83,12 +81,12 @@ git restore --staged --worktree $repo_root_directory
 echo "$diff" | git apply --index -
 
 # Commit changes
-if [ -z "$commit_message" ]; then
+if [ -n "$commit_message" ]; then
+    git commit -m "$commit_message"
+else
     # Request the commit message from the user
     # Also show the user the diff with --verbose when writing the message
     git commit --verbose
-else
-    git commit -m "$commit_message"
 fi
 
 git switch $current_branch
